name: "test workflow"

on:
  push:
    branches:
      - main

concurrency:
  group: dependencies
  cancel-in-progress: false

env:
  username: Krishna

jobs:
  intro:
    runs-on: ubuntu-latest
    steps:
      - name: user created
        run: |
          echo "app created by user $username "

  biuld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug paths
        run: |
          pwd
          ls -R


      - name: install dependencies
        run: npm install
        working-directory: ./app_setup

      - name: npm build
        run: npm run build
      
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist
      
      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
    
  test:
    runs-on: ubuntu-latest
    steps:
      - name: npm status
        run: npm --version

      - name: nodejs status
        run: nod --version



#  status:
#    runs-on: ubuntu-latest
#    need: build
