name: "test workflow"

on:
  push:
    branches:
      - main

env:
  username: Krishna
  name: sample

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: user created
          run: |
            echo "app created by user $username "
            sleep: 5
        
        - name: app name
          run: echo " name of the application is $name " 